package huncam.components.fragments.client;

import huncam.controller.AddToCartListener;
import huncam.model.Product;
import java.awt.Image;
import java.util.Locale;
import java.text.NumberFormat;
import javax.swing.ImageIcon;

public class CardProduct extends javax.swing.JPanel {

    private Product product;
    private AddToCartListener listener;

    public CardProduct(Product product) {
        initComponents(); // Method ini dibuat otomatis oleh NetBeans
        this.product = product;
        populateCard(); // Panggil method untuk mengisi data

        btnAddToCart.addActionListener(e -> {
            if (listener != null) {
                listener.onAddToCart(this.product);
            }
        });
    }

    public void setAddToCartListener(AddToCartListener listener) {
        this.listener = listener;
    }

    private void populateCard() {
        lbNameCard.setText(product.getName());
        Locale localId = new Locale("in", "ID");
        NumberFormat rupiah = NumberFormat.getCurrencyInstance(localId);
        lbPriceCard.setText(rupiah.format(product.getPrice()));

        try {
            ImageIcon originalIcon = new ImageIcon(getClass().getResource("/huncam/assets/product/" + product.getImagePath()));
            Image originalImage = originalIcon.getImage();
            Image scaledImage = originalImage.getScaledInstance(306, 200, Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            lbImageCard.setIcon(scaledIcon);
        } catch (Exception e) {
            lbImageCard.setText("Gambar Tidak Tersedia");
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbImageCard = new javax.swing.JLabel();
        lbNameCard = new javax.swing.JLabel();
        lbPriceCard = new javax.swing.JLabel();
        lbDescCard = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbImageCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/huncam/assets/product/Canon-EOS-RP.jpg"))); // NOI18N

        lbNameCard.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lbNameCard.setText("Canon EOS Rp");

        lbPriceCard.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbPriceCard.setForeground(new java.awt.Color(255, 153, 0));
        lbPriceCard.setText("Rp 12.000.000");

        lbDescCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDescCard.setText("Mirrorless kecil, full-frame, 26MP, 4K, Dual Pixel, Wi-Fi");

        btnAddToCart.setBackground(new java.awt.Color(0, 0, 0));
        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddToCart.setForeground(new java.awt.Color(255, 255, 255));
        btnAddToCart.setText("Add To Cart");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImageCard, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNameCard)
                            .addComponent(lbPriceCard))
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddToCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDescCard, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbImageCard, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPriceCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDescCard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddToCart, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed

    }//GEN-LAST:event_btnAddToCartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JLabel lbDescCard;
    private javax.swing.JLabel lbImageCard;
    private javax.swing.JLabel lbNameCard;
    private javax.swing.JLabel lbPriceCard;
    // End of variables declaration//GEN-END:variables
}
