/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package huncam.components.form.client;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author wilia
 */
public class HomeForm extends javax.swing.JPanel {

    private ArrayList<String> bannerImages;
    private int currentIndex = 0;

    public HomeForm() {
        initComponents();
        bannerImages = new ArrayList<>();
        bannerImages.add("C:/Users/wilia/project/huncam/src/huncam/assets/banner/banner-02.png");
        bannerImages.add("C:/Users/wilia/project/huncam/src/huncam/assets/banner/banner-04.jpg");

        showImage(currentIndex);
        wrapCategory1.categoryImage(new ImageIcon("C:/Users/wilia/project/huncam/src/huncam/assets/banner/sony.png"));
        wrapCategory2.categoryImage(new ImageIcon("C:/Users/wilia/project/huncam/src/huncam/assets/banner/nikon.png"));
        wrapCategory3.categoryImage(new ImageIcon("C:/Users/wilia/project/huncam/src/huncam/assets/banner/FujiFilm.png"));
        wrapCategory4.categoryImage(new ImageIcon("C:/Users/wilia/project/huncam/src/huncam/assets/banner/Canon.png"));
        
        

    }

    private void showImage(int img) {
        String imgPath = bannerImages.get(img);
        ImageIcon image = new ImageIcon(imgPath);
        Image image2 = image.getImage();

        Image image3 = image2.getScaledInstance(898, 350, Image.SCALE_SMOOTH);
        lbBanner.setIcon(new ImageIcon(image3));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerPanel = new javax.swing.JPanel();
        lbBanner = new javax.swing.JLabel();
        btnBackBanner = new javax.swing.JLabel();
        btnNextBanner = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        wrapCategory1 = new huncam.components.fragments.client.WrapCategory();
        wrapCategory2 = new huncam.components.fragments.client.WrapCategory();
        wrapCategory3 = new huncam.components.fragments.client.WrapCategory();
        wrapCategory4 = new huncam.components.fragments.client.WrapCategory();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        bannerPanel.setLayout(new java.awt.CardLayout());

        lbBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/huncam/assets/banner/banner-02.png"))); // NOI18N
        bannerPanel.add(lbBanner, "card2");

        btnBackBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/huncam/assets/icons/back.png"))); // NOI18N
        btnBackBanner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackBanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackBannerMouseClicked(evt);
            }
        });

        btnNextBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/huncam/assets/icons/right-arrow-1.png"))); // NOI18N
        btnNextBanner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNextBanner.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNextBannerMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Category Product");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(wrapCategory1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(wrapCategory2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(wrapCategory3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(wrapCategory4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(wrapCategory4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapCategory2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapCategory3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wrapCategory1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(btnBackBanner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextBanner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btnBackBanner))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnNextBanner)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextBannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextBannerMouseClicked
        currentIndex++;
        if (currentIndex >= bannerImages.size()) {
            currentIndex = 0;
        }
        showImage(currentIndex);
    }//GEN-LAST:event_btnNextBannerMouseClicked

    private void btnBackBannerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackBannerMouseClicked
        currentIndex--;
        if (currentIndex < 0) {
            currentIndex = bannerImages.size() - 1;
        }
        showImage(currentIndex);
    }//GEN-LAST:event_btnBackBannerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JLabel btnBackBanner;
    private javax.swing.JLabel btnNextBanner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbBanner;
    private huncam.components.fragments.client.WrapCategory wrapCategory1;
    private huncam.components.fragments.client.WrapCategory wrapCategory2;
    private huncam.components.fragments.client.WrapCategory wrapCategory3;
    private huncam.components.fragments.client.WrapCategory wrapCategory4;
    // End of variables declaration//GEN-END:variables
}
