package huncam.components.form.client;

import huncam.components.fragments.client.CardProduct;
import huncam.controller.AddToCartListener;
import huncam.controller.ProductController;
import huncam.model.Product;
import java.util.List;

public class ProductForm extends javax.swing.JPanel {
    
    private ProductController productController;
    private AddToCartListener cartListener;
    
    public ProductForm(AddToCartListener listener) {
        initComponents();
        
        this.productController = new ProductController();
        this.cartListener = listener;
        
        init();
    }
    
    private void init() {
        dislpayProduct("All");
    }
    
    private void dislpayProduct(String c) {
        mainPanel.removeAll();
        List<Product> productsList;
        
        if (c.equals("All")) {
            productsList = productController.getAllProduct();
        } else {
            productsList = productController.getProductByCategories(c);
        }
        
        for (Product product : productsList) {
            CardProduct card = new CardProduct(product);
            card.setAddToCartListener(this.cartListener);
            mainPanel.add(card);
        }
        
        mainPanel.revalidate();
        mainPanel.repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new javax.swing.JPanel();
        btnCanon = new javax.swing.JLabel();
        btnFujiFilm = new javax.swing.JLabel();
        btnNikon = new javax.swing.JLabel();
        btnSony = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(255, 255, 255));

        btnCanon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCanon.setText("Canon");
        btnCanon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCanon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCanonMouseClicked(evt);
            }
        });

        btnFujiFilm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnFujiFilm.setText("FujiFilm");
        btnFujiFilm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFujiFilm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFujiFilmMouseClicked(evt);
            }
        });

        btnNikon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNikon.setText("Nikon");
        btnNikon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNikon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNikonMouseClicked(evt);
            }
        });

        btnSony.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSony.setText("Sony");
        btnSony.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSony.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSonyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnCanon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242)
                .addComponent(btnFujiFilm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242)
                .addComponent(btnNikon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(242, 242, 242)
                .addComponent(btnSony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(157, 157, 157))
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCanon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFujiFilm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnNikon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(btnSony, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
        );

        add(headerPanel, java.awt.BorderLayout.PAGE_START);

        mainPanel.setLayout(new java.awt.GridLayout(0, 3, 10, 10));
        jScrollPane1.setViewportView(mainPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCanonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCanonMouseClicked
        dislpayProduct("Canon");
    }//GEN-LAST:event_btnCanonMouseClicked

    private void btnFujiFilmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFujiFilmMouseClicked
        dislpayProduct("FujiFilm");
    }//GEN-LAST:event_btnFujiFilmMouseClicked

    private void btnNikonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNikonMouseClicked
        dislpayProduct("Nikon");
    }//GEN-LAST:event_btnNikonMouseClicked

    private void btnSonyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSonyMouseClicked
        // TODO add your handling code here:
        dislpayProduct("Sony");
    }//GEN-LAST:event_btnSonyMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCanon;
    private javax.swing.JLabel btnFujiFilm;
    private javax.swing.JLabel btnNikon;
    private javax.swing.JLabel btnSony;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
